# permissions for end users to view googlekubernetesengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlekubernetesengine-viewer-role
rules:
- apiGroups:
  - knela.dev
  resources:
  - googlekubernetesengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - knela.dev
  resources:
  - googlekubernetesengines/status
  verbs:
  - get
