# permissions for end users to edit googlekubernetesengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: googlekubernetesengine-editor-role
rules:
- apiGroups:
  - knela.dev
  resources:
  - googlekubernetesengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - knela.dev
  resources:
  - googlekubernetesengines/status
  verbs:
  - get
